name: Update a mod 
description: Requests to add a mod 
title: "[Update]: {mod name}"
labels: ["Update"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
        value: |
         Thanks for taking the time to fill out this mod request!
  - type: input
    id: contact
    attributes:
      label: Mod Repository
      description: The Repository that we can find your mod
      placeholder: https://github.com/pecefulpro/BlankModKit
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of SSF2 is your mod running?
      options:
        - 1.3.1.1
        - 1.3.1.2 (Most Recent)
    validations:
      required: true
  - type: dropdown
    id: mod_type
    attributes:
      label: Explain why you are updating 
      multiple: true
      options:
        - Bug Fix
        - Version
        - Other
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: If you selected other tell us why?
      placeholder: Tell us what you see!
      value: "A problem happened."
    validations:
      required: false